version: "3"
services:

    nginx:
        image: nginx:1.19
        volumes:
            - "./.config/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - 9999:80
        networks:
            - gamehive-network
        depends_on:
            - appserver

    appserver:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./src:/src"
            - "./.config/postgres.env:/postgres.env"
        expose:
            - "5000"
        networks:
            - gamehive-network

    postgres:
        image: "library/postgres:9.6"
        env_file:
            - ./.config/postgres.env
        volumes:
            - postgres_db:/var/lib/postgresql/data
        expose:
            - "5432"
        networks:
            - gamehive-network

networks:
    gamehive-network:

volumes:
    postgres_db:
        driver: local
