version: "3"
services:

    nginx:
        image: nginx:1.19
        volumes:
            - "./default.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - 8001:80
        networks:
            - gamehive-network
        depends_on:
            - appserver

    appserver:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./src:/src"
        expose:
            - "5000"
        networks:
            - gamehive-network

    postgres:
        image: "library/postgres:9.6"
        environment:
            POSTGRES_USER: "gamehive"
            POSTGRES_PASSWORD: "gamehive"
        volumes:
            - postgres_db:/var/lib/postgresql/data
        expose:
            - "5432"
        networks:
            - gamehive-network

networks:
    gamehive-network:

volumes:
    postgres_db:
        driver: local
